# uses the local charts in the charts directory and images available locally
releases:
  - name: bitcoind
    namespace: sl
    chart: ../../charts/bitcoind
    values:
      - clientImage:
          repository: bitcoind-client
          pullPolicy: IfNotPresent
      - autoGen: true
  - name: alice
    namespace: sl
    chart: ../../charts/cln
    values:
      - clientImage:
          repository: cln-client
          pullPolicy: IfNotPresent
  - name: bob
    namespace: sl
    chart: ../../charts/cln
    values:
      - clientImage:
          repository: cln-client
          pullPolicy: IfNotPresent
  - name: carol
    namespace: sl
    chart: ../../charts/lnd
    values:
      - clientImage:
          repository: lnd-client
          pullPolicy: IfNotPresent
  - name: dave
    namespace: sl
    chart: ../../charts/lnd
    values:
      - clientImage:
          repository: lnd-client
          pullPolicy: IfNotPresent
  - name: timescaledb
    namespace: sl
    chart: ../../charts/timescaledb
  - name: torq
    namespace: sl
    chart: ../../charts/torq
