apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: port
      targetPort: port
      port: {{ .Values.port }}
  selector:
    {{- include "timescaledb.selectorLabels" . | nindent 4 }}
