apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "timescaledb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timescaledb.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
      volumes:
        - name: data
          {{- if .Values.volume.size }}
          persistentVolumeClaim:
            claimName: {{ include "timescaledb.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          ports:
            - name: port
              containerPort: {{ .Values.port }}
          env:
            - name: POSTGRES_PASSWORD
              value: "runningtorq"
