nameOverride: ""
fullnameOverride: ""

image:
  repository: timescale/timescaledb
  tag: latest-pg14
  pullPolicy: IfNotPresent

port: 5432

# set to one of the endpoints defined in traefik's values file e.g. (endpoint1, endpoint2, endpoint3, endpoint4)
# to expose direct TCP access to the database
tcpEntryPoint: endpoint1

# This gives persistence to nodes. If no storage is set then the node will be ephemeral between upgrades.
volume:
  # example 1Gi for 1 gibibyte (1024^3 bytes). Blank string for no storage.
  size: ""
  # example do-block-storage for DigitalOcean's standard block storage. Blank for default storage class.
  storageClass: ""
