# Default values for helm.
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

image:
  repository: lightninglabs/lnd
  tag: v0.16.4-beta
  pullPolicy: IfNotPresent

clientImage:
  repository: scalingln/lnd-client
  tag: latest
  pullPolicy: Always

rpcPort: 8332

rpcUser: foo
rpcPass: pass
rpcHost: bitcoind
zmqPubBlockPort: 28332
zmqPubTxPort: 28333

port: 9735
gRPCPort: 10009
restPort: 8080

clientPort: 8181

network: regtest

# set to one of the endpoints defined in traefik's values file e.g. (endpoint1, endpoint2, endpoint3, endpoint4)
# to expose direct gRPC access to the node
gRPCEntryPoint: null

# This gives persistence to nodes. If no storage is set then the node will be ephemeral between upgrades.
volume:
  size: "" # example 1Gi for 1 gibibyte (1024^3 bytes). Blank string for no storage.
  storageClass: "" # example do-block-storage for DigitalOcean's standard block storage. Blank for default storage class.
